import { CalendarDays, Check, FileText, MessageSquareText, Sparkles, UploadCloud } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { StatusBadge } from "@/components/ui/StatusBadge";

export function DashboardPreview() {
  const reduce = useReducedMotion();
  return (
    <motion.div initial={reduce ? false : { opacity: 0, y: 28, rotateX: 6 }} whileInView={{ opacity: 1, y: 0, rotateX: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .9, ease: [0.22, 1, 0.36, 1] }} className="relative overflow-hidden rounded-[38px] border border-white/10 bg-[var(--ink)] p-3 shadow-[0_55px_150px_rgba(11,18,32,.3)] sm:p-4 lg:p-5">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_25%_0%,rgba(36,87,255,.18),transparent_38%),radial-gradient(circle_at_100%_100%,rgba(70,214,166,.12),transparent_34%)]" />
      <div className="relative grid min-h-[585px] overflow-hidden rounded-[29px] bg-[var(--paper)] lg:grid-cols-[190px_1fr]">
        <aside className="hidden border-r border-black/7 bg-white/75 p-4 lg:flex lg:flex-col"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-[var(--ink)] text-[color:var(--mint)]"><Sparkles className="size-3.5" /></span><span className="font-extrabold tracking-[-.04em]">Orée</span></div><nav className="mt-8 space-y-1">{["Vue d'ensemble", "Mon projet", "Orientation", "Documents", "Formalités", "Messages"].map((label, i) => <div key={label} className={`flex items-center gap-2 rounded-xl px-3 py-2.5 text-[11px] font-bold ${i === 0 ? "bg-[var(--ink)] text-white" : "text-[color:var(--muted)]"}`}><span className={`size-1.5 rounded-full ${i === 0 ? "bg-[var(--mint)]" : "bg-[var(--line-strong)]"}`} />{label}</div>)}</nav><div className="mt-auto rounded-[18px] bg-[var(--paper)] p-3"><p className="text-[9px] font-extrabold uppercase tracking-[.12em] text-[color:var(--muted)]">Suivi du projet</p><div className="mt-3 flex items-center gap-2"><span className="grid size-8 place-items-center rounded-full bg-[var(--mint)] text-[10px] font-extrabold">OR</span><div><p className="text-[10px] font-extrabold">Équipe Orée</p><p className="text-[8px] text-[color:var(--muted)]">Données illustratives</p></div></div></div></aside>
        <div className="p-3 sm:p-5 lg:p-6">
          <div className="flex items-center justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-[.13em] text-[color:var(--muted)]">Vue du projet</p><h3 className="mt-1 text-xl font-semibold tracking-[-.055em] sm:text-2xl">Progression du dossier</h3></div><span className="rounded-full border border-[var(--line)] bg-white px-3 py-2 text-[9px] font-semibold text-[color:var(--muted)]">Aperçu</span></div>
          <div className="mt-4 grid gap-3 sm:grid-cols-[1.25fr_.75fr]">
            <div className="relative overflow-hidden rounded-[23px] bg-[var(--ink)] p-5 text-white"><div className="absolute -right-12 -top-16 size-40 rounded-full bg-[var(--accent)]/28 blur-3xl" /><p className="relative text-[9px] font-extrabold uppercase tracking-[.13em] text-white/72">Progression globale</p><div className="relative mt-4 flex items-end justify-between"><div><p className="text-4xl font-semibold tracking-[-.07em]">64%</p><p className="mt-2 text-[10px] text-white/72">Vérification documentaire</p></div><span className="grid size-11 place-items-center rounded-full bg-[var(--mint)] text-[color:var(--ink)]"><Check className="size-4" /></span></div><div className="relative mt-5 h-1.5 overflow-hidden rounded-full bg-white/8"><motion.div className="h-full rounded-full bg-[linear-gradient(90deg,var(--mint),var(--sky))]" initial={reduce ? { width: "64%" } : { width: 0 }} whileInView={{ width: "64%" }} viewport={{ once: true }} transition={{ duration: 1.2, delay: .25 }} /></div></div>
            <div className="rounded-[23px] border border-[var(--line)] bg-white p-4"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-[14px] bg-[var(--mint-soft)]"><CalendarDays className="size-4" /></span><span className="text-[9px] font-extrabold uppercase text-[color:var(--success)]">Confirmé</span></div><p className="mt-5 text-[10px] font-bold text-[color:var(--muted)]">Prochain rendez-vous</p><p className="mt-1 text-sm font-extrabold">Jeudi · 16:30</p><p className="mt-1 text-[9px] text-[color:var(--muted)]">Validation de l'orientation</p></div>
          </div>
          <div className="mt-3 grid gap-3 md:grid-cols-2">
            <div className="rounded-[23px] border border-[var(--line)] bg-white p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-[.12em] text-[color:var(--muted)]">Action prioritaire</p><h4 className="mt-2 text-sm font-extrabold">Remplacer le justificatif</h4></div><StatusBadge status="changes_requested" /></div><p className="mt-3 text-[10px] leading-5 text-[color:var(--muted)]">Transmettez un document lisible datant de moins de trois mois.</p><span className="mt-4 inline-flex items-center gap-2 rounded-full bg-[var(--ink)] px-3 py-2 text-[9px] font-extrabold text-white"><UploadCloud className="size-3.5" />Nouvelle version</span></div>
            <div className="rounded-[23px] border border-[var(--line)] bg-white p-4"><div className="flex items-center justify-between"><p className="text-[9px] font-extrabold uppercase tracking-[.12em] text-[color:var(--muted)]">Activité récente</p><MessageSquareText className="size-4 text-[color:var(--accent)]" /></div><div className="mt-4 space-y-3">{[{ icon: FileText, text: "Pièce d'identité validée", time: "09:42" }, { icon: MessageSquareText, text: "Nouveau message de l'équipe", time: "Hier" }].map((item) => { const Icon = item.icon; return <div key={item.text} className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-xl bg-[var(--paper)]"><Icon className="size-3.5" /></span><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-extrabold">{item.text}</p><p className="mt-0.5 text-[8px] text-[color:var(--muted)]">{item.time}</p></div></div>; })}</div></div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
