import { ArrowRight, ArrowUpRight, CalendarCheck2, CircleDollarSign, Clock3, Sparkles, Target, UserCheck } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { ButtonLink } from "@/components/ui/Button";
import { mockLeads } from "@/data/mock";
import { usePageMeta } from "@/hooks/usePageMeta";

const metrics = [
  { label: "Nouveaux leads", value: "24", change: "+18%", icon: Sparkles, note: "vs. période précédente" },
  { label: "Leads qualifiés", value: "11", change: "+9%", icon: UserCheck, note: "46% du volume" },
  { label: "Rendez-vous", value: "8", change: "+3", icon: CalendarCheck2, note: "6 confirmés" },
  { label: "Temps de rappel", value: "12 min", change: "-5 min", icon: Clock3, note: "objectif < 15 min" },
] as const;

export default function OpsDashboardPage() {
  usePageMeta("Pilotage opérationnel", "Suivez les leads, la qualification et la progression commerciale.");
  return <div className="mx-auto max-w-[1540px] space-y-5 sm:space-y-6">
    <section className="hero-grid surface-noise relative overflow-hidden rounded-[32px] bg-[var(--night)] p-6 text-white sm:p-8 lg:p-10"><div className="relative z-10 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.13em] text-white/72"><span className="size-2 rounded-full bg-[var(--mint)] shadow-[0_0_16px_var(--mint)]" />Données de démonstration</div><h2 className="mt-5 max-w-4xl text-balance text-4xl font-semibold leading-[.96] tracking-[-.06em] sm:text-5xl lg:text-6xl">Priorisez les demandes selon <span className="gradient-text">leur maturité et leur échéance.</span></h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/72">La vue opérationnelle classe les demandes à partir de l'intention, du niveau d'avancement, du calendrier et des actions déjà réalisées.</p></div><ButtonLink to="/ops/leads" variant="dark">Traiter la file prioritaire <ArrowRight className="size-4" /></ButtonLink></div></section>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric, index) => { const Icon = metric.icon; return <Card key={metric.label} className="interactive-card p-5 sm:p-6"><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-[18px] bg-[var(--night)] text-white"><Icon className="size-5" /></span><span className="inline-flex items-center gap-1 rounded-full bg-[var(--mint-soft)] px-2.5 py-1 text-[11px] font-bold text-[color:var(--success)]"><ArrowUpRight className="size-3" />{metric.change}</span></div><div className="mt-6 flex items-end justify-between gap-4"><div><p className="text-3xl font-semibold tracking-[-.055em] sm:text-4xl">{metric.value}</p><p className="mt-1 text-sm font-semibold">{metric.label}</p><p className="mt-2 text-[11px] text-[color:var(--muted)]">{metric.note}</p></div><span className="text-5xl font-semibold text-[color:var(--ink)]/[.04]">0{index + 1}</span></div></Card>; })}</div>

    <div className="grid gap-5 xl:grid-cols-[1.38fr_.62fr]">
      <Card className="overflow-hidden"><div className="flex flex-col gap-4 border-b border-[var(--line)] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[color:var(--muted)]">File prioritaire</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.035em]">Demandes à traiter</h2></div><ButtonLink to="/ops/leads" variant="ghost" className="h-auto p-0 text-[color:var(--accent)]">Voir toutes les demandes <ArrowRight className="size-4" /></ButtonLink></div><div className="overflow-x-auto scrollbar-thin"><table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-[var(--line)] bg-black/[.018] text-[10px] font-bold uppercase tracking-[.11em] text-[color:var(--muted)]"><th className="px-5 py-3.5">Demande</th><th className="px-5 py-3.5">Projet</th><th className="px-5 py-3.5">Source</th><th className="px-5 py-3.5">Score</th><th className="px-5 py-3.5">Statut</th><th className="px-5 py-3.5">Reçu</th></tr></thead><tbody>{mockLeads.map((lead) => <tr key={lead.id} className="group border-b border-[var(--line)] last:border-0 transition hover:bg-[var(--mint-soft)]/35"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[14px] bg-[var(--night)] text-[10px] font-extrabold text-white">{lead.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><div><p className="text-sm font-semibold">{lead.name}</p><p className="mt-1 text-[10px] text-[color:var(--muted)]">{lead.id}</p></div></div></td><td className="px-5 py-4"><p className="text-sm font-semibold">{lead.project}</p><p className="mt-1 text-[11px] text-[color:var(--muted)]">{lead.intent}</p></td><td className="px-5 py-4"><span className="rounded-full border border-[var(--line)] bg-white px-2.5 py-1 text-[11px] font-semibold">{lead.source}</span></td><td className="px-5 py-4"><span className={`grid size-10 place-items-center rounded-full text-xs font-extrabold ${lead.score >= 80 ? "bg-[var(--mint)] text-[color:var(--ink)]" : lead.score >= 65 ? "bg-[var(--amber)]/35 text-[color:var(--ink)]" : "bg-black/[.05] text-[color:var(--muted)]"}`}>{lead.score}</span></td><td className="px-5 py-4"><span className="rounded-full bg-[var(--accent)]/9 px-3 py-1.5 text-[11px] font-bold text-[color:var(--accent-deep)]">{lead.status}</span></td><td className="px-5 py-4 text-xs text-[color:var(--muted)]">{lead.age}</td></tr>)}</tbody></table></div></Card>
      <div className="space-y-5">
        <Card className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[color:var(--muted)]">Qualification</p><h3 className="mt-2 text-lg font-semibold">Répartition du jour</h3></div><span className="grid size-11 place-items-center rounded-[17px] bg-[var(--mint-soft)]"><Target className="size-5" /></span></div><div className="mt-7 space-y-5">{[["Très haute priorité", 6, "var(--mint-strong)"], ["À qualifier", 9, "var(--accent)"], ["À relancer", 5, "var(--amber)"], ["Invalide ou hors cible", 4, "rgba(11,18,32,.22)"]].map(([label, value, color]) => <div key={String(label)}><div className="flex items-center justify-between text-sm"><span className="font-medium">{label}</span><strong>{value}</strong></div><div className="mt-2.5 h-2 overflow-hidden rounded-full bg-black/[.05]"><div className="h-full rounded-full" style={{ width: `${Number(value) * 7}%`, background: String(color) }} /></div></div>)}</div></Card>
        <Card className="hero-grid surface-noise overflow-hidden bg-[var(--night)] p-5 text-white sm:p-6"><div className="relative z-10 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-white/72">Valeur commerciale</p><h3 className="mt-2 font-semibold">Objectif à connecter</h3></div><CircleDollarSign className="size-5 text-[color:var(--mint)]" /></div><p className="relative z-10 mt-6 text-3xl font-semibold tracking-[-.055em]">customer_won</p><p className="relative z-10 mt-3 text-sm leading-6 text-white/72">Le CRM doit renvoyer les leads qualifiés et clients gagnés vers Google Ads, pas seulement les formulaires soumis.</p></Card>
      </div>
    </div>
  </div>;
}
