import { useState } from "react";
import { Save, ShieldCheck, UserRound } from "lucide-react";
import { ActionNotice } from "@/components/feedback/ActionNotice";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { usePageMeta } from "@/hooks/usePageMeta";

export default function OpsProfilePage() {
  const [saved, setSaved] = useState(false);
  const [profile, setProfile] = useState({ name: "Membre de l'équipe Orée", email: "equipe@exemple.fr", availability: "09:00 – 18:00" });
  usePageMeta("Profil opérations", "Gérez les informations de présentation et les préférences du compte équipe.");
  return <div className="mx-auto max-w-5xl space-y-6"><section className="hero-grid surface-noise rounded-[32px] bg-[var(--night)] p-7 text-white sm:p-10"><span className="grid size-13 place-items-center rounded-[18px] bg-[var(--mint)] text-[color:var(--ink)]"><UserRound className="size-5" /></span><h1 className="mt-6 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Profil du compte équipe</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/72">Les informations de profil n'accordent aucun rôle interne. Les autorisations restent gérées exclusivement côté serveur.</p></section>{saved ? <ActionNotice title="Profil enregistré" description="Les modifications sont conservées localement dans cette démonstration." onClose={() => setSaved(false)} /> : null}<Card className="p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Nom affiché<input value={profile.name} onChange={(event) => setProfile((current) => ({ ...current, name: event.target.value }))} className="mt-2 h-12 w-full rounded-2xl border border-[var(--line)] px-4 font-normal outline-none focus:border-[var(--blue)]" /></label><label className="text-sm font-semibold">Adresse professionnelle<input type="email" value={profile.email} onChange={(event) => setProfile((current) => ({ ...current, email: event.target.value }))} className="mt-2 h-12 w-full rounded-2xl border border-[var(--line)] px-4 font-normal outline-none focus:border-[var(--blue)]" /></label><label className="text-sm font-semibold sm:col-span-2">Plage de disponibilité<input value={profile.availability} onChange={(event) => setProfile((current) => ({ ...current, availability: event.target.value }))} className="mt-2 h-12 w-full rounded-2xl border border-[var(--line)] px-4 font-normal outline-none focus:border-[var(--blue)]" /></label></div><div className="mt-6 flex flex-col gap-4 border-t border-[var(--line)] pt-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3 text-xs leading-5 text-[color:var(--muted)]"><ShieldCheck className="mt-0.5 size-4 shrink-0" />Le rôle et les permissions ne peuvent pas être modifiés depuis cette page.</div><Button onClick={() => { localStorage.setItem("oree:ops-profile:v1", JSON.stringify(profile)); setSaved(true); }}><Save className="size-4" />Enregistrer</Button></div></Card></div>;
}
