import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { CalendarDays, Check, CircleAlert, FileCheck2, FileText, MessageSquareText, Plus, Sparkles, UploadCloud } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { ButtonLink } from "@/components/ui/Button";
import { ProgressRing } from "@/components/ui/ProgressRing";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { portalRepository } from "@/services/supabase/portal";
import { usePageMeta } from "@/hooks/usePageMeta";

export default function DashboardPage() {
  usePageMeta("Vue d'ensemble du projet", "Suivez les actions, documents, messages et rendez-vous de votre projet.");
  const { data, isLoading, error } = useQuery({ queryKey: ["portal", "snapshot"], queryFn: portalRepository.getSnapshot, refetchInterval: 30_000 });
  const [renderedAt] = useState(() => Date.now());
  if (isLoading) return <Card className="mx-auto max-w-5xl p-10 text-center text-sm text-[color:var(--muted)]">Chargement de votre espace sécurisé…</Card>;
  if (error) return <Card className="mx-auto max-w-5xl border-[var(--blue)]/20 p-8 text-[color:var(--blue)]">{error instanceof Error ? error.message : "Impossible de charger le projet."}</Card>;
  if (!data?.project) return <div className="mx-auto max-w-4xl"><Card className="hero-grid surface-noise overflow-hidden bg-[var(--night)] p-8 text-center text-white sm:p-12"><span className="mx-auto grid size-15 place-items-center rounded-[20px] bg-[var(--mint)] text-[color:var(--ink)]"><Plus className="size-6" /></span><h1 className="mt-7 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Votre compte est prêt.</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-white/72">Aucun projet n’est encore associé à ce compte. Lancez un diagnostic avec la même adresse email pour créer une continuité sécurisée, ou contactez l’équipe si une demande existe déjà.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><ButtonLink to="/diagnostic" variant="accent">Démarrer un diagnostic</ButtonLink><ButtonLink to="/app/messages" variant="dark">Contacter l’équipe</ButtonLink></div></Card></div>;

  const project = data.project;
  const pendingDocuments = data.documents.filter((document) => ["required", "changes_requested", "rejected"].includes(document.status));
  const receivedDocuments = data.documents.filter((document) => !["required", "not_requested"].includes(document.status)).length;
  const unread = data.messages.filter((message) => !message.isOwn && !message.read).length;
  const nextAppointment = [...data.appointments].filter((appointment) => Date.parse(appointment.startsAt) > renderedAt && !["cancelled", "completed", "no_show"].includes(appointment.status)).sort((a, b) => Date.parse(a.startsAt) - Date.parse(b.startsAt))[0];
  const priority = pendingDocuments[0];

  return <div className="mx-auto max-w-[1480px] space-y-5">
    <section className="hero-grid surface-noise relative overflow-hidden rounded-[36px] bg-[var(--ink)] p-6 text-white sm:p-9 lg:p-11"><div className="relative grid gap-8 xl:grid-cols-[1fr_360px] xl:items-end"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.055] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.13em] text-white/72"><span className="size-2 rounded-full bg-[var(--mint)]" />{data.demo ? "Mode démonstration" : "Espace Supabase privé"}</div><h1 className="mt-6 max-w-4xl text-balance text-4xl font-semibold leading-[.95] tracking-[-.06em] sm:text-6xl">{priority ? "Une action documentaire conditionne la suite." : "Votre projet reste lisible, étape par étape."}</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/72">{project.displayName} · {project.legalForm ?? "forme à confirmer"} · étape {project.status.replaceAll("_", " ")}.</p><div className="mt-7 flex flex-wrap gap-3"><ButtonLink to={priority ? "/app/documents" : "/app/projet"} variant="accent">{priority ? <UploadCloud className="size-4" /> : <Sparkles className="size-4" />}{priority ? `Traiter : ${priority.label}` : "Vérifier les informations"}</ButtonLink><ButtonLink to="/app/messages" variant="dark"><MessageSquareText className="size-4" />Écrire à l’équipe</ButtonLink></div></div><div className="rounded-[28px] border border-white/10 bg-white/[.055] p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-white/72">Progression</p><p className="mt-2 text-xl font-semibold">{project.status.replaceAll("_", " ")}</p></div><ProgressRing value={project.progress} size={104} /></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-[var(--mint)]" style={{ width: `${project.progress}%` }} /></div></div></div></section>

    <div className="grid gap-4 sm:grid-cols-3">{[[`${receivedDocuments}/${data.documents.length}`, "Documents reçus", FileCheck2],[String(unread), "Messages non lus", MessageSquareText],[nextAppointment ? new Date(nextAppointment.startsAt).toLocaleDateString("fr-FR", { day: "2-digit", month: "short" }) : "—", "Prochain rendez-vous", CalendarDays]].map(([value,label,Icon]) => { const IconComponent = Icon as typeof FileCheck2; return <Card key={String(label)} className="flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-[16px] bg-[var(--mint-soft)]"><IconComponent className="size-4.5" /></span><div><p className="text-2xl font-semibold">{String(value)}</p><p className="mt-1 text-xs text-[color:var(--muted)]">{String(label)}</p></div></Card>; })}</div>

    {priority ? <Card className="route-map border-[var(--blue)]/20 p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid size-12 shrink-0 place-items-center rounded-[18px] bg-[var(--blue)] text-white"><CircleAlert className="size-5" /></span><div className="flex-1"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[color:var(--blue)]">Action prioritaire</p><h2 className="mt-2 text-2xl font-semibold">{priority.label}</h2><p className="mt-2 text-sm leading-6 text-[color:var(--muted)]">{priority.comment || "Un document est attendu pour poursuivre le traitement du dossier."}</p></div><ButtonLink to="/app/documents">Ouvrir le centre documentaire</ButtonLink></div></Card> : null}

    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line)] p-5 sm:p-6"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[color:var(--muted)]">Documents</p><h2 className="mt-2 text-2xl font-semibold">État du dossier</h2></div><ButtonLink to="/app/documents" variant="ghost" size="sm">Tout voir</ButtonLink></div><div className="divide-y divide-[var(--line)]">{data.documents.slice(0, 6).map((document) => <div key={document.id} className="flex items-center gap-4 p-5"><span className="grid size-10 place-items-center rounded-[14px] bg-[var(--paper)]"><FileText className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{document.label}</p><p className="mt-1 text-xs text-[color:var(--muted)]">{document.category}</p></div><StatusBadge status={document.status} /></div>)}</div></Card>
      <div className="space-y-5"><Card className="p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">Derniers événements</h2><ButtonLink to="/app/suivi" variant="ghost" size="sm">Chronologie</ButtonLink></div><div className="mt-6 space-y-5">{data.timeline.slice(0, 5).map((event) => <div key={event.id} className="flex gap-3"><span className={`mt-1 grid size-7 shrink-0 place-items-center rounded-full ${event.state === "done" ? "bg-[var(--mint)]" : "bg-[var(--blue)] text-white"}`}>{event.state === "done" ? <Check className="size-3" /> : <Sparkles className="size-3" />}</span><div><p className="text-sm font-semibold">{event.title}</p><p className="mt-1 text-xs leading-5 text-[color:var(--muted)]">{event.description}</p><p className="mt-1 text-[10px] text-[color:var(--muted)]">{new Date(event.date).toLocaleString("fr-FR")}</p></div></div>)}{data.timeline.length === 0 ? <p className="text-sm text-[color:var(--muted)]">Aucun événement enregistré.</p> : null}</div></Card>{nextAppointment ? <Card className="p-6"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[color:var(--muted)]">Prochain rendez-vous</p><h3 className="mt-3 text-2xl font-semibold">{new Date(nextAppointment.startsAt).toLocaleString("fr-FR", { dateStyle: "long", timeStyle: "short" })}</h3><p className="mt-2 text-sm text-[color:var(--muted)]">Statut : {nextAppointment.status}</p><ButtonLink to="/app/rendez-vous" variant="secondary" className="mt-5 w-full">Voir le calendrier</ButtonLink></Card> : null}</div>
    </div>
  </div>;
}
