import { useQuery } from "@tanstack/react-query";
import { Check, CircleAlert, GitBranch, Scale, Sparkles } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { ButtonLink } from "@/components/ui/Button";
import { AppPageHero } from "@/components/app/AppPageHero";
import { getLegalForm } from "@/data/legalForms";
import { usePageMeta } from "@/hooks/usePageMeta";
import { portalRepository } from "@/services/supabase/portal";

export default function OrientationPage() {
  usePageMeta("Orientation du projet", "Comparez les structures envisagées et les points restant à valider.");
  const { data, error } = useQuery({ queryKey: ["portal", "snapshot"], queryFn: portalRepository.getSnapshot });
  const orientation = data?.orientation;
  const codes = Array.from(new Set([orientation?.currentForm, ...(orientation?.consideredForms ?? [])].filter((value): value is string => Boolean(value))));
  const forms = codes.map(getLegalForm).filter((form): form is NonNullable<typeof form> => Boolean(form));
  const primary = orientation?.currentForm ?? forms[0]?.code ?? null;
  const reasons = orientation?.reasons ?? [];
  const validationPoints = orientation?.validationPoints ?? [];

  return <div className="mx-auto max-w-6xl space-y-5">
    <AppPageHero icon={GitBranch} eyebrow="Orientation actuelle" title={primary ? <>La piste enregistrée est <span className="gradient-text">{primary}.</span></> : <>Votre orientation reste <span className="gradient-text">à construire.</span></>} description={primary ? "Cette orientation provient du dossier et reste une hypothèse à confirmer avec les paramètres sociaux, fiscaux, juridiques et personnels pertinents." : "Complétez le diagnostic pour faire apparaître des structures à comparer et les points qui devront être confirmés."} stat={{ value: String(validationPoints.length), label: "Points à valider" }} action={<ButtonLink to={primary ? "/app/rendez-vous" : "/diagnostic"} variant="dark">{primary ? "Planifier une validation" : "Faire le diagnostic"}</ButtonLink>} />
    {error ? <Card className="border-[var(--blue)]/20 bg-[var(--blue)]/8 p-5 text-sm">{error instanceof Error ? error.message : "Chargement impossible"}</Card> : null}

    <Card className="overflow-hidden"><div className="border-b border-[var(--line)] p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[color:var(--muted)]">Comparaison enregistrée</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.04em]">{forms.length ? `${forms.length} structure${forms.length > 1 ? "s" : ""} à approfondir` : "Aucune structure enregistrée"}</h3></div>{forms.length ? <div className="grid gap-4 p-5 sm:p-7 md:grid-cols-2">{forms.map((form) => { const isPrimary = form.code === primary; return <article key={form.code} className={`interactive-card rounded-[28px] border p-6 ${isPrimary ? "border-[var(--accent)]/35 bg-[var(--paper)] shadow-[0_24px_70px_rgba(36,87,255,.09)]" : "border-[var(--line)] bg-white/75"}`}><div className="flex items-center justify-between"><span className="text-4xl font-semibold tracking-[-.06em]">{form.code}</span><span className={`rounded-full px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.08em] ${isPrimary ? "bg-[var(--accent)] text-white" : "bg-[var(--paper)] text-[color:var(--muted)]"}`}>{isPrimary ? "Piste principale" : "Alternative"}</span></div><p className="mt-5 text-sm leading-7 text-[color:var(--muted)]">{form.summary}</p><div className="mt-6 space-y-3">{form.bestFor.slice(0, 3).map((item) => <div key={item} className="flex items-start gap-2.5 text-sm"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-[var(--mint-soft)]"><Check className="size-3" /></span>{item}</div>)}</div><div className="mt-6 border-t border-[var(--line)] pt-5"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[color:var(--muted)]">Régime du dirigeant</p><p className="mt-2 text-sm leading-6">{form.socialRegime}</p></div></article>; })}</div> : <div className="p-8 text-center text-sm leading-6 text-[color:var(--muted)]">Aucun résultat de diagnostic n’est encore lié à ce projet.</div>}</Card>

    <div className="grid gap-5 lg:grid-cols-[1fr_360px]">
      <Card className="p-6 sm:p-8"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-[18px] bg-[var(--mint-soft)]"><Scale className="size-5" /></span><div><h3 className="text-lg font-semibold">Éléments du diagnostic</h3><p className="text-xs text-[color:var(--muted)]">{orientation?.definitionVersion ? `Questions ${orientation.definitionVersion} · règles ${orientation.ruleVersion ?? "—"}` : "Aucune version liée"}</p></div></div><div className="mt-7 space-y-4">{reasons.length ? reasons.map((item, index) => <div key={`${index}-${item}`} className="flex gap-4 rounded-[20px] border border-[var(--line)] bg-white/65 p-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[var(--night)] text-[10px] font-extrabold text-white">{String(index + 1).padStart(2, "0")}</span><p className="pt-1 text-sm leading-6 text-[color:var(--muted)]">{item}</p></div>) : <p className="rounded-[20px] bg-[var(--paper)] p-5 text-sm leading-6 text-[color:var(--muted)]">Les raisons détaillées apparaîtront ici lorsqu’un diagnostic terminé sera rattaché au projet.</p>}</div></Card>
      <div className="space-y-5"><Card className="border-[var(--blue)]/20 bg-[var(--blue)]/8 p-5"><div className="flex items-center gap-2"><CircleAlert className="size-5" /><h3 className="font-semibold">À valider</h3></div>{validationPoints.length ? <ul className="mt-4 space-y-3 text-sm leading-6 text-[color:var(--ink)]/70">{validationPoints.map((point) => <li key={point}>• {point}</li>)}</ul> : <p className="mt-4 text-sm leading-6 text-[color:var(--ink)]/70">Aucun point spécifique n’est enregistré. Une validation humaine reste recommandée avant toute décision.</p>}<ButtonLink to="/app/rendez-vous" className="mt-5 w-full">Planifier la validation</ButtonLink></Card><Card className="hero-grid surface-noise overflow-hidden bg-[var(--night)] p-5 text-white"><div className="relative z-10"><Sparkles className="size-5 text-[color:var(--mint)]" /><h3 className="mt-4 font-semibold">Orientation auditable</h3><p className="mt-2 text-sm leading-6 text-white/72">Les versions de questions et de règles restent associées au résultat afin d’expliquer l’orientation sans la présenter comme un conseil définitif.</p></div></Card></div>
    </div>
  </div>;
}
