import { Check, CircleAlert, GitBranch, Scale, Sparkles } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { ButtonLink } from "@/components/ui/Button";
import { AppPageHero } from "@/components/app/AppPageHero";
import { getLegalForm } from "@/data/legalForms";
import { usePageMeta } from "@/hooks/usePageMeta";

export default function OrientationPage() {
  usePageMeta("Orientation du projet", "Comparez les structures envisagées et les points restant à valider.");
  const forms = [getLegalForm("SASU")!, getLegalForm("EURL")!];
  return <div className="mx-auto max-w-6xl space-y-5">
    <AppPageHero icon={GitBranch} eyebrow="Orientation actuelle" title={<>La SASU constitue <span className="gradient-text">l'hypothèse principale à examiner.</span></>} description="Cette piste paraît cohérente avec un projet de conseil porté seul et susceptible d'accueillir ultérieurement un associé. Les raisons, les alternatives et les points à confirmer restent accessibles." stat={{ value: "2", label: "Points à valider" }} action={<ButtonLink to="/app/rendez-vous" variant="dark">Valider l'orientation</ButtonLink>} />

    <Card className="overflow-hidden"><div className="border-b border-[var(--line)] p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[color:var(--muted)]">Comparaison active</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Deux structures à approfondir</h3></div><div className="grid gap-4 p-5 sm:p-7 md:grid-cols-2">{forms.map((form, index) => <article key={form.code} className={`interactive-card rounded-[28px] border p-6 ${index === 0 ? "border-[var(--accent)]/35 bg-[linear-gradient(145deg,rgba(36,87,255,.08),rgba(247,245,239,.86))] shadow-[0_24px_70px_rgba(36,87,255,.09)]" : "border-[var(--line)] bg-white/75"}`}><div className="flex items-center justify-between"><span className="text-4xl font-semibold tracking-[-.06em]">{form.code}</span>{index === 0 ? <span className="rounded-full bg-[var(--accent)] px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.08em] text-white">Piste principale</span> : <span className="rounded-full bg-[var(--paper)] px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.08em] text-[color:var(--muted)]">Alternative</span>}</div><p className="mt-5 text-sm leading-7 text-[color:var(--muted)]">{form.summary}</p><div className="mt-6 space-y-3">{form.bestFor.slice(0, 3).map((item) => <div key={item} className="flex items-start gap-2.5 text-sm"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-[var(--mint-soft)]"><Check className="size-3" /></span>{item}</div>)}</div><div className="mt-6 border-t border-[var(--line)] pt-5"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[color:var(--muted)]">Dirigeant</p><p className="mt-2 text-sm leading-6">{form.socialRegime}</p></div></article>)}</div></Card>

    <div className="grid gap-5 lg:grid-cols-[1fr_360px]">
      <Card className="p-6 sm:p-8"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-[18px] bg-[var(--mint-soft)]"><Scale className="size-5" /></span><div><h3 className="text-lg font-semibold">Pourquoi cette orientation ?</h3><p className="text-xs text-[color:var(--muted)]">Raisons issues du diagnostic version 1</p></div></div><div className="mt-7 space-y-4">{["Le projet est porté par une seule personne et vise une activité de conseil structurée.", "L'arrivée future d'un associé ou d'un investisseur fait partie des priorités déclarées.", "Le besoin de crédibilité commerciale est plus important que la simplicité absolue du régime micro.", "Le calendrier permet de préparer les statuts et documents sans urgence excessive."].map((item, index) => <div key={item} className="flex gap-4 rounded-[20px] border border-[var(--line)] bg-white/65 p-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[var(--night)] text-[10px] font-extrabold text-white">0{index + 1}</span><p className="pt-1 text-sm leading-6 text-[color:var(--muted)]">{item}</p></div>)}</div></Card>
      <div className="space-y-5"><Card className="border-[var(--blue)]/20 bg-[var(--blue)]/8 p-5"><div className="flex items-center gap-2 text-[color:var(--ink)]"><CircleAlert className="size-5" /><h3 className="font-semibold">À valider</h3></div><ul className="mt-4 space-y-3 text-sm leading-6 text-[color:var(--ink)]/70"><li>• Mode de rémunération pendant la première année</li><li>• Protection sociale souhaitée</li><li>• Calendrier d'entrée d'un associé éventuel</li></ul><ButtonLink to="/app/rendez-vous" className="mt-5 w-full">Planifier la validation</ButtonLink></Card><Card className="hero-grid surface-noise overflow-hidden bg-[var(--night)] p-5 text-white"><div className="relative z-10"><Sparkles className="size-5 text-[color:var(--mint)]" /><h3 className="mt-4 font-semibold">Orientation auditable</h3><p className="mt-2 text-sm leading-6 text-white/72">La version des règles et les réponses du diagnostic sont conservées afin de comprendre le résultat plus tard.</p></div></Card></div>
    </div>
  </div>;
}
