import { Check, Clock3, Filter, Gauge, MessageSquareText } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { AppPageHero } from "@/components/app/AppPageHero";
import { ButtonLink } from "@/components/ui/Button";
import { mockTimeline } from "@/data/mock";
import { usePageMeta } from "@/hooks/usePageMeta";

export default function TrackingPage() {
  const [filter, setFilter] = useState<"all" | "done" | "current" | "upcoming">("all");
  const visibleEvents = filter === "all" ? mockTimeline : mockTimeline.filter((event) => event.state === filter);
  usePageMeta("Suivi du projet", "Consultez la chronologie, les événements et les prochaines étapes du projet.");
  return <div className="mx-auto max-w-6xl space-y-5">
    <AppPageHero icon={Gauge} eyebrow="Chronologie du projet" title={<>Chaque événement reste <span className="gradient-text">compréhensible.</span></>} description="Le suivi distingue les actions terminées, l'étape actuelle et les objectifs futurs, sans confondre les délais internes avec ceux de l'administration." stat={{ value: "64%", label: "Progression" }} action={<label className="inline-flex h-11 items-center gap-2 rounded-full border border-white/12 bg-white/[.07] px-4 text-sm font-semibold text-white"><Filter className="size-4" /><span className="sr-only">Filtrer la chronologie</span><select value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)} className="bg-transparent outline-none"><option value="all" className="text-[color:var(--ink)]">Toutes les étapes</option><option value="done" className="text-[color:var(--ink)]">Terminées</option><option value="current" className="text-[color:var(--ink)]">Étape actuelle</option><option value="upcoming" className="text-[color:var(--ink)]">À venir</option></select></label>} />
    <div className="grid gap-5 lg:grid-cols-[1fr_330px]"><Card className="p-6 sm:p-8"><div className="relative space-y-0">{visibleEvents.map((event, index) => <div key={event.id} className="relative flex gap-5 pb-8 last:pb-0"><div className="relative z-10"><span className={`grid size-11 place-items-center rounded-full border-4 border-white ${event.state === "done" ? "bg-[var(--mint)]" : event.state === "current" ? "bg-[var(--blue)] text-white" : "bg-[var(--paper)] text-[color:var(--muted)]"}`}>{event.state === "done" ? <Check className="size-4" /> : event.state === "current" ? <Clock3 className="size-4" /> : index + 1}</span>{index < visibleEvents.length - 1 ? <span className="absolute left-1/2 top-11 h-[calc(100%+2rem)] w-px -translate-x-1/2 bg-[var(--line)]" /> : null}</div><div className={`flex-1 rounded-[22px] border p-4 ${event.state === "current" ? "border-[var(--blue)] bg-blue-50/60" : "border-[var(--line)] bg-white"}`}><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold">{event.title}</h3><p className="mt-2 text-sm leading-6 text-[color:var(--muted)]">{event.description}</p></div><span className="shrink-0 text-xs font-semibold text-[color:var(--muted)]">{event.date}</span></div>{event.state === "current" ? <div className="mt-4 flex flex-wrap gap-2"><ButtonLink to="/app/documents" size="sm">Voir l'action</ButtonLink><ButtonLink to="/app/messages" variant="ghost" size="sm"><MessageSquareText className="size-4" />Poser une question</ButtonLink></div> : null}</div></div>)}{visibleEvents.length === 0 ? <p className="py-10 text-center text-sm text-[color:var(--muted)]">Aucun événement ne correspond à ce filtre.</p> : null}</div></Card><div className="space-y-5"><Card className="p-5"><p className="text-xs font-semibold uppercase tracking-[.13em] text-[color:var(--muted)]">Progression</p><p className="mt-3 text-4xl font-semibold tracking-[-.05em]">64%</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-[var(--ink)]/8"><div className="h-full w-[64%] rounded-full bg-[var(--mint)]" /></div><div className="mt-5 grid grid-cols-2 gap-3">{[["2", "étapes terminées"], ["1", "action active"], ["3", "étapes futures"], ["0", "retard signalé"]].map(([value, label]) => <div key={label} className="rounded-2xl bg-[var(--paper)] p-3"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] leading-4 text-[color:var(--muted)]">{label}</p></div>)}</div></Card><Card className="p-5"><h3 className="font-semibold">À propos des délais</h3><p className="mt-3 text-sm leading-6 text-[color:var(--muted)]">La plateforme peut afficher les délais internes de traitement. Les délais administratifs externes restent indicatifs et ne doivent pas être présentés comme garantis.</p></Card></div></div>
  </div>;
}
import { useState } from "react";
